Update patch set 1
Patch Set 1:

device/samsung/i9300/audio/audio_hw.c: In function 'select_devices':
device/samsung/i9300/audio/audio_hw.c:341:9: error: expected ')' before '!' token
         !(adev->dev_cfgs[i].mask & AUDIO_DEVICE_BIT_IN))

Missing &&.

Patch-set: 1
Reviewer: Gerrit User 1000285 <1000285@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0